<a href="https://colab.research.google.com/github/rahuljungbahadur/hands_on_ml_book/blob/main/chp12_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises From chapter 12

## Do you get the same result with tf.range(10) and tf.constant(np.arange(10))?

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.constant(np.arange(10))

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

The later one has a default data type of `int64` (higher precision). Whereas the tensorflow one has a dtype of `int32` (lower precision)

## Sample python function converted to tensorlfow

In [ ]:
@tf.function
def sum_squares(n):
  s=0
  for i in range(n):
    s+=i**2
  
  return s


In [ ]:
sum_squares  ## It is a python funcition

In [ ]:
tf.autograph.to_code(sum_squares.python_function)

"def tf__sum_squares(n):\n    with ag__.FunctionScope('sum_squares', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:\n        do_return = False\n        retval_ = ag__.UndefinedReturnValue()\n        s = 0\n\n        def get_state():\n            return (s,)\n\n        def set_state(vars_):\n            nonlocal s\n            (s,) = vars_\n\n        def loop_body(itr):\n            nonlocal s\n            i = itr\n            s = ag__.ld(s)\n            s += (i ** 2)\n        i = ag__.Undefined('i')\n        ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(n),), None, fscope), None, loop_body, get_state, set_state, ('s',), {'iterate_names': 'i'})\n        try:\n            do_return = True\n            retval_ = ag__.ld(s)\n        except:\n            do_return = False\n            raise\n        return fscope.ret(retval_, do_return)\n"

In [ ]:
def tf__sum_squares(n):
    with ag__.FunctionScope('sum_squares', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        s = 0

        def get_state():
            return (s,)

        def set_state(vars_):
            nonlocal s
            (s,) = vars_

        def loop_body(itr):
            nonlocal s
            i = itr
            s = ag__.ld(s)
            s += (i ** 2)
        i = ag__.Undefined('i')
        ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(n),), None, fscope), None, loop_body, get_state, set_state, ('s',), {'iterate_names': 'i'})
        try:
            do_return = True
            retval_ = ag__.ld(s)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)


This way you can see the tensorflow generated code

## Autodiff example

In [ ]:
def f(w1, w2):
  return 3* w1**2 + 2*w1*w2

In [ ]:
f(2,3)

24

In [ ]:
f(tf.Variable(5), tf.Variable(3)) ## Same result

<tf.Tensor: shape=(), dtype=int32, numpy=105>

In [ ]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)

with tf.GradientTape() as tape:
  z=f(w1, w2)

gradients=tape.gradient(z, [w1, w2])

In [ ]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [ ]:
def loger(x):
  return tf.math.sin(x)

In [ ]:
w3 = tf.Variable(1.)

with tf.GradientTape() as tape:
  q = loger(w3)

grads = tape.gradient(q, [w3])

In [ ]:
grads

[<tf.Tensor: shape=(), dtype=float32, numpy=0.5403023>]

## Implement a custom layer that performs Layer Normalization (we will use this type of layer in Chapter 15):

In [ ]:
from tensorflow.python.ops.gen_math_ops import betainc
class LayerNorm(tf.keras.layers.Layer):

  ## Init layer
  def __init__(self, **kwargs):
    super().__init__(**kwargs)

  def build(self, input_batch_shape):

    ## alpha
    alpha_init=tf.initializers.Ones()

    self.alpha = tf.Variable(initial_value=alpha_init(shape=input_batch_shape[-1:]),
                        name='alpha',
                        dtype=tf.float32)
    
    ## beta
    beta_init = tf.initializers.Zeros()

    self.beta = tf.Variable(initial_value=beta_init(shape=input_batch_shape[-1:]),
                       name='beta',
                       dtype=tf.float32)
    
    super().build(input_batch_shape)

  ## call method

  def call(self, X):

    mean, var = tf.nn.moments(X, axes=-1, keepdims=True)
    sd = tf.math.sqrt(var)

    return tf.multiply(self.alpha, (X-mean)/(sd+0.001)) + self.beta



In [ ]:
sample_matrix = tf.Variable([[1,2], [3,4]], dtype=tf.float32)
sample_matrix

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
custom_layer = LayerNorm()

In [ ]:
custom_layer(sample_matrix)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.998004,  0.998004],
       [-0.998004,  0.998004]], dtype=float32)>

In [ ]:
from tensorflow.keras.layers import LayerNormalization

In [ ]:
std_layer = LayerNormalization()

In [ ]:
std_layer(sample_matrix)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.99800605,  0.99800605],
       [-0.99800605,  0.99800605]], dtype=float32)>

Qns 13 Train a model using a custom training loop to tackle the Fashion MNIST dataset (see Chapter 10).

Display the epoch, iteration, mean training loss, and mean accuracy over each epoch (updated at each iteration), as well as the validation loss and accuracy at the end of each epoch.

Try using a different optimizer with a different learning rate for the upper layers and the lower layers.

In [108]:
from tensorflow.keras.datasets import mnist

In [109]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [115]:
n_epochs = 5
batch_size = 1
n_steps = len(X_train) // batch_size
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)
loss_fn = tf.keras.losses.categorical_crossentropy
mean_loss = tf.keras.metrics.Mean()
metrics = [tf.keras.metrics.Accuracy()]

In [118]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

In [116]:
X_train.shape

(60000, 28, 28)

In [117]:
28*28

784

In [114]:
model = Sequential()

model.add(Flatten(input_shape=[28,28]))

model.add(Dense(500, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam', loss='categoroical_crossentropy')

In [ ]:
model.add

In [119]:
def print_status_bar(iteration, total, loss, metrics=None):
    metrics = " - ".join(["{}: {:.4f}".format(m.name, m.result())
                         for m in [loss] + (metrics or [])])
    end = "" if iteration < total else "\n"
    print("\r{}/{} - ".format(iteration, total) + metrics,
          end=end)

In [ ]:
for epoch in n_epochs:
  print(epoch)
  for step in range(1, n_steps+1):
    print(f'iteration number {step}')
    with tf.GradientTape() as tape:
      y_pred = model(X_train, training = True)

      ## loss
      step_loss = tf.reduce_mean(tf.keras.losses.categorical_crossentropy(y_true=y_train, y_pred=y_pred)) ## per step
      print(f'iteration loss {step_loss}')

      ## step accuracy
      step_accuracy = tf.metrics.Accuracy(y_train, y_pred)
      print(f'iteration accuracy {step_accuracy}')


      ## Error gradients
    gradients = tape.gradient(step_loss, model.trainable_variables)

    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    ## Mean loss per epoch
    mean_epoch_loss = tf.keras.metrics.Mean(step_loss)

    print(mean_epoch_loss)

    ## Mean accuracy per epoch
    mean_epoch_accuracy = tf.reduce_mean(step_accuracy)

    print(mean_epoch_accuracy)


