<a href="https://colab.research.google.com/github/rahuljungbahadur/hands_on_ml_book/blob/main/chp18_reinforcement_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gym

env = gym.make("CartPole-v1")
obs = env.reset()

In [ ]:
obs

array([-0.03053545, -0.04242501, -0.02687926,  0.04269137])

In [ ]:
# gym.envs.registry.all()

In [ ]:
env.action_space

Discrete(2)

In [ ]:
env.reset()

array([ 0.01905671,  0.01398968, -0.00050029,  0.03515599])

In [ ]:
action=1
obs, reward, done, info= env.step(action)

In [ ]:
obs

array([ 0.02351888,  0.40423786, -0.00495087, -0.55030369])

In [ ]:
reward

1.0

In [ ]:
done

False

In [ ]:
info

{}

In [ ]:
def basic_policy(obs):
  angle=obs[2]
  return 0 if angle < 0 else 1

totals=[]

for episode in range(500):
  episode_rewards=0
  obs=env.reset()
  for step in range(200):
        action = basic_policy(obs)
        obs, reward, done, info = env.step(action)
        episode_rewards += reward
        if done:
            break
  totals.append(episode_rewards)


In [ ]:
import numpy as np

In [ ]:
np.mean(totals), np.std(totals), np.min(totals), np.max(totals)

(42.276, 8.535093672596686, 24.0, 68.0)